export const HOLDING_STATUS = {
    UPCOMMING: "UPCOMMING",
    POOLING: "POOLING",
    TRADING: "TRADING",
    SETTLEMENT: "SETTLEMENT",
    CLOSED: "CLOSED",
    UNKNOWN: "UNKNOWN",
  };

 export const BASE_URL= process.env.BASE_URL ;